stages:
  - build
  - deploy
  - remove
image: docker

variables:
   DOCKER_HOST: ""

build-job:
  stage: build
  script:
    - echo "Start build job"
    - docker build -f Dockerfile -t tst2.ru-central1.internal:5000/tst .
    - docker push tst2.ru-central1.internal:5000/tst

deploy:
  stage: deploy
  image: tst2.ru-central1.internal:5000/myhelm
  script:
    - kubectl apply -f k3s/.
  allow_failure: true

remove:
  stage: remove
  script:
    - docker-compose down
  when: manual
