apiVersion: v1
kind: Service
metadata:
  labels:
    app: tst
  name: tst
  namespace: java
spec:
  type: NodePort
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30007
  selector:
    app: tst