app:                               ### блок про деплой ### 
  name: tst                  # название приложения
  standName:                       # полезная переменная для выкатки на разные стенды
  secretName: hello-secret         # имя файла с секретами
  #branch: develop                  # полезная переменная для передачи в аннтоцию имени ветки
  replicas: 1                     # количество реплик для приложения

image:                             ### блок про образ ###
  app: tst2.ru-central1.internal:5000/tst     # имя образа
  tag:  latest                     # тег образа
  
service:                           ### блок про сервис ###
  internalPort: 8000                # порт внутренний
  externalPort: 30007                # порт внешний

sample:                            ### блок про переменные ###
  env: 123                         # здесь могла бы быть ваша переменная
  

tst_port: "8000"

config:                            
  env: "456"                       # здесь могла бы быть ваша переменная для конфигмапы

limits:                            ### блок про лимиты ###
  cpu: "1"                         # 2 ядра, если приложение потребует больше, оно будет тормозить
  memory: "1Gi"                    # 4Гб ОЗУ, если приложение потребует больше, придёт ООМ killer :)

requests:                          ### блок про реквесты (минимальные значения для запуска приложения) ###
  cpu: "100m"                      # 0.1 ядра, 260Мб ОЗУ - тут мы указываем, что приложению необходимо минимум вот столько
  memory: "260Mi"                  # соответственно sheduler назначит под на ноду, где есть столько ресурсов

hpa:                               ### блок про hpa ###
  enable: false                     # включён если true
  min_pod_count: 2                 # минимальное количество реплик
  max_pod_count: 6                 # максимальное количество реплик
  averageUtilization: 50           # средняя нагрузка на процессор для запуска новой реплики

pdb:                               ### блок про hpa ###
  enable: false                    # включён если true
  minAvailable: 2                  # минимальное количество доступных реплик